name: ci-workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome step
        run: echo "Welcome to GitHub"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Repository Information
        run: |
          echo "Repository Name: ${{ github.repository }}"
          echo "Type of Event: ${{ github.event_name }}"
          git --version
          git branch
          git log --oneline
